name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '3.0', '3.1.x', '5.0.x' ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore src/Biscuit/Biscuit.sln
    - name: Build
      run: dotnet build --no-restore src/Biscuit/Biscuit.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal src/Biscuit/Biscuit.sln
